main:
  clusterGroupName: datacenter
  multiSourceConfig:
    enabled: true

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: fvosburgh3
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: fvosburgh
    #username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  s3:
    bucket:
      name: acm-demo
      region: us-east-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
